# Generated by Django 3.1.6 on 2021-02-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_auto_20210223_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speech',
            name='summary',
            field=models.TextField(help_text='Enter speech here', max_length=2000),
        ),
    ]
