# Generated by Django 3.1.6 on 2021-02-24 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_auto_20210224_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='speech',
            name='biography',
            field=models.TextField(blank=True, help_text='Enter biography here', max_length=2000, null=True),
        ),
    ]
