# Generated by Django 3.1.6 on 2021-02-24 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_speech_biography'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speech',
            name='biography',
        ),
        migrations.AddField(
            model_name='speaker',
            name='biography',
            field=models.TextField(blank=True, help_text='Enter biography here', max_length=2000, null=True),
        ),
    ]
