# Generated by Django 3.1.6 on 2021-02-24 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0006_auto_20210224_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='biography',
            field=models.TextField(blank=True, help_text='Enter biography here', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='speech',
            name='summary',
            field=models.TextField(help_text='Enter speech here', max_length=10000),
        ),
    ]
