# Generated by Django 3.1.6 on 2021-02-24 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0007_auto_20210224_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speech',
            name='summary',
            field=models.TextField(help_text='Enter speech here'),
        ),
    ]
