# Generated by Django 3.1.6 on 2021-02-26 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0012_auto_20210224_1646'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
